// packages/vue/components/Modal/index.vue
<script>
  import Guide from './Guide';
  import s from '../../../common/Modal/index.scss';

  let MOUSE_POS = {};
  window.addEventListener('click', onClickWindow, true);
  function onClickWindow(event) {
    const clientRect = event.target.getBoundingClientRect();

    MOUSE_POS = {
      x: clientRect.left,
      y: clientRect.top
    };
  };

  export default {
    Guide,
    name: 'l-modal',
    components: {
      'l-button': () => import('../Button')
    },
    props: {
      visible: { type: Boolean, default: true },
      title: { type: String, default: '' },
      onDone: { type: Function },
      onCancel: { type: Function },
      onDismiss: { type: Function }
    },
    methods: {
      enter(el) {
        document.documentElement.style.overflow = 'hidden';
        this.musePosition = MOUSE_POS;

        this.$refs.modal.style = `
          opacity: 0;
          transform: scale(0.3);
          left: ${MOUSE_POS.x}px;
          top: ${MOUSE_POS.y}px;
          transform-origin: 0px 0px;
        `;

        document.body.append(el);
        setTimeout(()=> this.$refs.modal.style = '', 0);
      },
      leave() {
        this.$refs.modal.style = `
          opacity: 0;
          transform: scale(0.3);
          left: ${this.musePosition.x}px;
          top: ${this.musePosition.y}px;
          transform-origin: 0px 0px;
        `;
      }
    },
    data: ()=> ({
      s,
      musePosition: {},
      overlayStyle: ''
    })
  }
</script>

<template>
  <transition
    @enter="enter"
    @leave="leave"
    :duration="300"
  >
    <div v-if="visible">
      <div
        ref="overlay"
        :class="s.overlay"
        @click="()=> onDismiss && onDismiss()"
      />

      <div ref="modal" :class="s.modal">
        <div :class="s.case">
          <div :class="s.title">{{title}}</div>
          <div :class="s.content">
            <slot />
          </div>
        </div>

        <div :class="s.actions">
          <l-button
            v-if="onCancel"
            size='s'
            variant='text'
            @click.native="onCancel"
          >Отмена</l-button>

          <l-button
            v-if="onDone"
            size='s'
            :class="s.action"
            @click.native="onDone"
          >Ок</l-button>
        </div>
      </div>
    </div>
  </transition>
</template>

// packages/react/components/Modal/index.js
import React, { useState, useEffect } from 'react';
// import Button from '../Button';
import Portal from '../Portal';
import { c } from '../../helpers';
import guide from './index.mdx';
import s from './index.scss';

let MOUSE_POS = {};

window.addEventListener('click', clickMouse, true);
function clickMouse(e) {
  const scrollTop = document.documentElement.scrollTop;

  MOUSE_POS = {
    x: e.pageX,
    y: e.pageY - scrollTop
  };
};

function Modal({
  children,
  // style,
  className,
  visible,
  // onDone,
  onDismiss
  // onCancel
}) {
  const [step, setStep] = useState('close');
  const [mousePositions, setMousePositions] = useState({});
  const [_style, setStyle] = useState({});

  useEffect(()=> {
    if (visible) {
      show();
    } else if (step === 'show') {
      hide();
    }
  }, [visible]);

  function show() {
    setStep('render');
    setMousePositions(MOUSE_POS);

    setStyle({
      left: MOUSE_POS.x,
      top: MOUSE_POS.y,
      transformOrigin: `0px ${MOUSE_POS.y - 300}px`
    });

    setTimeout(()=> {
      setStyle({});
      setStep('show');
    }, 100);
  }

  function hide() {
    setStep('render');

    setStyle({
      left: mousePositions.x,
      top: mousePositions.y,
      transformOrigin: `0px ${mousePositions.y - 300}px`
    });

    setTimeout(()=> {
      setStyle({});
      setStep('close');
    }, 300);
  }

  let title = null;
  let content = null;
  const actions = [];
  const other = [];
  React.Children.toArray(children).forEach(child=> {
    if (child.type.name === ModalTitle.name) {
      title = child;
      return;
    }

    if (child.type.name === ModalContent.name) {
      content = child;
      return;
    }

    if (child.type.name === ModalActions.name) {
      actions.push(child);
      return;
    }

    other.push(child);
  });

  // render
  // animation
  return (
    <Portal>
      {
        step !== 'close' &&
        <>
          <div className={s.overlay} onClick={onDismiss} />
          <div
            className={c(s.modal, { [s.show]: step === 'show' }, className)}
            style={_style}
          >
            <div className={s.case}>
              {
                !!title &&
                <div className={s.title}>{title}</div>
              }

              <div className={s.content}>{content || other}</div>
            </div>

            <div className={s.actions}>
              {!!actions && actions}

              {
                !actions &&
                <div></div>
              }
            </div>
          </div>
        </>
      }
    </Portal>
  );
};

Modal.guide = guide;

function ModalTitle({ children }) {
  return children;
};

function ModalContent({ children }) {
  return children;
};

function ModalActions({ children }) {
  return children;
};

Modal.Title = ModalTitle;
Modal.Content = ModalContent;
Modal.Actions = ModalActions;
export default Modal;
