// packages/vue/components/Rating/index.vue
<script>
  import Guide from './Guide';
  import s from '../../../common/Rating/index.scss';

  export default {
    Guide,
    name: 'l-rating',
    props: {
      value: { type: Number, default: 50 },
      total: { type: Number, default: 100 },
      count: { type: Number, default: 5 }
    },
    data() {
      return {
        s,
        hoverIndex: -1,
        activeIndex: -1
      }
    }
  }
</script>

<template>
  <div
    :class="s.loftRating"
    @mouseleave="hoverIndex = -1"
  >
    <div
      v-for="_, index in new Array(5).fill(true)"
      :class="[s.loftRatingItem, {
        [s.loftRatingItemHover]: index <= hoverIndex,
        [s.loftRatingItemActive]: index <= activeIndex
      }]"
      @mousemove="hoverIndex = index"
      v-on:click="activeIndex = index"
    />
  </div>
</template>

// packages/react/components/Rating/index.js
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import { c } from '../../helpers';
import guide from './index.mdx';
import s from './index.scss';

// isHalf
// classIcon
// classIconActive
// classIconSelect
/*
  {
    value,
    total,
    count,
    onChange
  }
*/

function Rating() {
  const [activeIndex, setActiveIndex] = useState(-1);
  const [hoverIndex, setHoverIndex] = useState(-1);

  return (
    <div
      className={s.loftRating}
      onMouseLeave={()=> setHoverIndex(-1)}
    >
      {
        new Array(5).fill(true).map((item, index)=> (
          <div
            className={c(s.loftRatingItem, {
              [s.loftRatingItemHover]: index <= hoverIndex,
              [s.loftRatingItemActive]: index <= activeIndex
            })}
            onMouseMove={()=> setHoverIndex(index)}
            onClick={()=> setActiveIndex(index)}
          />
        ))
      }
    </div>
  );

}

Rating.guide = guide;

Rating.defaultProps = {
  value: 50,
  total: 100,
  count: 5
};

Rating.propTypes = {
  value: PropTypes.number,
  total: PropTypes.number,
  count: PropTypes.count
};

export default Rating;
