// packages/svelte/components/Tooltip/Tooltip.svelte
<script>
  import s from '../../../common/Tooltip/index.scss';

  export let visible = false;
  export let content;

  let step = 'exited';
  let _visible = false;
  let refContent;
  let refCaption;

  function onMouseOver () {
    visible = true;
  }

  function onMouseLeave () {
    visible = false;
  }

  $: popoverStyle = (()=> {
    if (visible) {
      if (step === 'exited' && visible) _visible = true;
      if (step === 'exited' && refCaption && refContent) {
        const captionRect = refCaption.getBoundingClientRect();
        const contentRect = refContent.getBoundingClientRect();
        const topPosition = captionRect.top + document.documentElement.scrollTop;

        setTimeout(()=> step = 'entered', 0);

        return `
          top: ${topPosition - contentRect.height - 5}px;
          left: ${captionRect.left + (captionRect.width / 2) - (contentRect.width / 2)}px;
          opacity: 0;
        `;
      }
      if (step === 'entered') {
        const captionRect = refCaption.getBoundingClientRect();
        const contentRect = refContent.getBoundingClientRect();
        const topPosition = captionRect.top + document.documentElement.scrollTop;

        return `
          top: ${topPosition - contentRect.height - 5}px;
          left: ${captionRect.left + (captionRect.width / 2) - (contentRect.width / 2)}px;
          opacity: 1;
        `;
      }
    }

    if (!visible) {
      if (step === 'entered' && refCaption) {
        const captionRect = refCaption.getBoundingClientRect();
        const contentRect = refContent.getBoundingClientRect();
        const topPosition = captionRect.top + document.documentElement.scrollTop;

        setTimeout(()=> step = 'exited', 300);

        return `
          top: ${topPosition - contentRect.height - 5}px;
          left: ${captionRect.left + (captionRect.width / 2) - (contentRect.width / 2)}px;
          opacity: 0;
        `;
      }
      if (step === 'exited') {
        _visible = false;
        return '';
      }
    }
  })()
</script>

<div>
  <div
    on:mouseover={onMouseOver}
    on:mouseleave={onMouseLeave}
    bind:this={refCaption}
  >
    <slot />
  </div>
  {#if _visible}
    <div
      style={popoverStyle}
      class={s.content}
      bind:this={refContent}
    >
      <svelte:component this={content} />
    </div>
  {/if}
</div>

// packages/vue/components/Tooltip/index.vue
<script>
  import Guide from './Guide';
  import s from '../../../common/Tooltip/index.scss';

  export default {
    Guide,
    name: 'l-tooltip',
    props: {
      className: { type: String },
      content: { type: Object }
    },
    mounted() {
      const caption = this.$slots.default[0].elm;
      caption.addEventListener('mouseover', this.onMouseOver);
    },
    methods: {
      onMouseOver() {
        const caption = this.$slots.default[0].elm;
        caption.addEventListener('mouseleave', this.onMouseLeave);
        this.visible = true;
      },
      onMouseLeave() {
        const caption = this.$slots.default[0].elm;
        this.visible = false;
        caption.removeEventListener('mouseleave', this.onMouseLeave);
      },
      enter(el) {
        const captionRect = this.$slots.default[0].elm.getBoundingClientRect();
        const contentRect = this.$refs.content.$el.getBoundingClientRect();
        const topPosition = captionRect.top + document.documentElement.scrollTop;

        this.$refs.content.$el.style = `
          top: ${topPosition - contentRect.height - 5}px;
          left: ${captionRect.left + (captionRect.width / 2) - (contentRect.width / 2)}px;
          opacity: 0;
        `;

        document.body.append(el);
        setTimeout(()=> {
          this.$refs.content.$el.style = `
            top: ${topPosition - contentRect.height - 5}px;
            left: ${captionRect.left + (captionRect.width / 2) - (contentRect.width / 2)}px;
            opacity: 1;
          `;
        }, 0);
      },
      leave() {
        const captionRect = this.$slots.default[0].elm.getBoundingClientRect();
        const contentRect = this.$refs.content.$el.getBoundingClientRect();
        const topPosition = captionRect.top + document.documentElement.scrollTop;

        this.$refs.content.$el.style = `
          top: ${topPosition - contentRect.height - 5}px;
          left: ${captionRect.left + (captionRect.width / 2) - (contentRect.width / 2)}px;
          opacity: 0;
        `;
      }
    },
    components: {
      'l-popover': ()=> import('../Popover')
    },
    data: ()=> ({
      s,
      visible: false
    })
  }
</script>

<template>
  <div>
    <slot />
    <transition
      @enter="enter"
      @leave="leave"
      :duration="300"
    >
      <component
        v-if="visible"
        ref="content"
        :is="content"
        :class="s.content"
      />
    </transition>
  </div>
</template>
