// packages/svelte/components/Modal/Guide.svelte
<script>
  import { Code, InlineCode as I } from '../../helpers';
  import Modal from './Modal.svelte';
  import Button from '../Button';

  let visible = false;
</script>

<h1>Modal</h1>
<p>Скрытая часть появляющаяся поверх всего. Как правило по середине</p>
<Code v={`import { Modal } from 'loft-ui';`} lang='js' />

<h2>Простой пример</h2>
<Button
  on:click={()=> visible = true}
>Открыть</Button>
<Modal
  visible={visible}
  onDismiss={()=> visible = false}
  onCancel={()=> visible = false}
  onDone={()=> visible = false}
>Контент</Modal>

// packages/vue/components/Modal/Guide.vue
<script>
  import { Code, InlineCode as I } from '../../helpers';

  export default {
    components: {
      I, Code,
      'l-modal': () => import('./'),
      'l-button': () => import('../Button')
    },
    data: ()=> ({
      visible: false
    })
  }
</script>

<template>
  <div>
    <h1>Modal</h1>
    <p>Скрытая часть появляющаяся поверх всего. Как правило по середине</p>
    <Code v="import { l-modal } from 'loft-ui';" />

    <h2>Простой пример</h2>
    <l-button @click.native="visible = !visible">
      Открыть
    </l-button>
    <l-modal
      title="Пример"
      :visible="visible"
      :onDismiss="()=> visible = false"
      :onCancel="()=> visible = false"
      :onDone="()=> visible = false"
    >Контент</l-modal>
  </div>
</template>
