// packages/vue/components/Collapse/Guide.vue
<script>
  import { Code, InlineCode as I } from '../../helpers';

  export default {
    components: {
      I, Code,
      'l-button': () => import('../Button'),
      'l-collapse': () => import('./')
    },
    data: ()=> ({
      visible: false,
      visible2: false
    })
  }
</script>

<template>
  <div>
    <h1>Сollapse</h1>
    <p>С помощью чекбоксов пользователь выбирает элементы из списка данных</p>
    <Code v="import { l-collapse } from 'loft-ui'" />

    <h2>Простой пример</h2>
    <l-collapse :visible="visible">
      <div style="padding: 8px; box-sizing: border-box;">
        <div>111</div>
        <div>111</div>
        <div>111</div>

        <l-collapse :visible="visible2">
          <div>222</div>
          <div>222</div>
          <div>222</div>
        </l-collapse>
        <l-button @click.native="visible2 = !visible2">
          {{ visible2 ? 'Скрыть' : 'Открыть' }}
        </l-button>
      </div>
    </l-collapse>
    <l-button @click.native="visible = !visible">
      {{ visible ? 'Скрыть' : 'Открыть' }}
    </l-button>
  </div>
</template>

// packages/svelte/components/Checkbox/Guide.svelte
<script>
  import { Code, InlineCode as I } from '../../helpers';
  import Checkbox from './Checkbox';

  let actives = [false, true];
</script>

<h1>Checkbox</h1>
<p>С помощью чекбоксов пользователь выбирает элементы из списка данных</p>
<Code v={`import { Checkbox } from 'loft-ui';`} lang='js' />

<h2>Простой пример</h2>
<Code v={`
  <script>
    let selected = false;
  </script>

  <Checkbox
    selected={selected}
    on:click={()=> selected = !selected}
  />
`} />
<div>
  <Checkbox
    selected={actives[0]}
    on:click={()=> actives[0] = !actives[0]}
  >Default</Checkbox>
  <Checkbox
    selected={actives[1]}
    on:click={()=> actives[1] = !actives[1]}
  >Checked</Checkbox>
</div>
