// packages/vue/components/AutoComplete/index.vue
<script>
  import Guide from './Guide';
  import Content from './Content';
  import s from '../../../common/AutoComplete/index.scss';

  export default {
    Guide,
    name: 'l-autoComplete',
    props: {
      value: { type: Object, default: ()=> ({}) },
      data: { type: Array, default: ()=> ([]) },
      label: { type: String, default: 'Select value' },
      onChange: { type: Function }
    },
    components: {
      'l-popover': () => import('../Popover'),
      'l-input': () => import('../Input')
    },
    computed: {
      dataFilter() {
        return this.data.filter(item => {
          return this.inputValue
            ? !!item.label.match(new RegExp('^' + this.inputValue, 'gi'))
            : true;
        });
      },
      content: ()=> Content,
      contentProps() {
        return {
          data: this.dataFilter,
          active: this.value.value,
          onChange: (value, label)=> {
            this.onChange({ value, label })
          }
        }
      }
    },
    data: ()=> ({
      s,
      inputValue: '',
      showPopover: false
    })
  }
</script>

<template>
  <l-popover
    :className="s.popover"
    :visible="showPopover"
    :hasWidthCaption="true"
    :content="content"
    :contentProps="contentProps"
  >
    <l-input
      variant="outline"
      :label="label"
      :value="showPopover ? inputValue : value.label"
      @input="inputValue = $event.target.value"
      @focus="showPopover = true"
      @blur="showPopover = false"
    />
  </l-popover>
</template>

// packages/react/components/AutoComplete/index.jsx
import React, { useEffect, useRef, useState } from 'react';
import Input from '../Input';
import Popvoer from '../Popover';
import Menu from '../Menu';
import Guide from './Guide';
import c from 'clsx';
import s from '../../../common/AutoComplete/index.scss';
import sInput from '../../../common/Input/index.scss';

function AutoComplete ({
  label = 'Select value',
  data = [],
  value = {},
  onChange
}) {
  const _data = useRef();
  const [inputValue, setInputValue] = useState('');
  const [showPopover, setShowPopover] = useState(false);

  _data.current = data.filter(item => {
    return inputValue
      ? !!item.label.match(new RegExp('^' + inputValue, 'gi'))
      : true;
  });

  function _onChange (value, label) {
    onChange({ value, label });
    setShowPopover(false);
  }

  function onDismiss () {
    setInputValue('');
    setShowPopover(false);
  }

  const content = (
    <Menu
      variant="vertical"
      active={value.value}
      onChange={_onChange}
    >{
      _data.current.map(item=> (
        <Menu.Item value={item.value}>{item.label}</Menu.Item>
      ))
    }</Menu>
  );

  return (
    <Popvoer
      content={content}
      hasWidthCaption={true}
      visible={showPopover}
      className={s.popover}
      onDismiss={onDismiss}
    >
      <Input
        variant="outline"
        label={label}
        value={showPopover ? inputValue : value.label}
        className={c({ [sInput.inputFocus]: showPopover })}
        onFocus={()=> setShowPopover(true)}
        onChange={t=> setInputValue(t)}
      />
    </Popvoer>
  );
}

AutoComplete.Guide = Guide;

export default AutoComplete;
