// packages/react/components/Loader/index.jsx
import React from 'react';
import PropTypes from 'prop-types';
import Guide from './Guide';
import c from 'clsx';
import s from '../../../common/Loader/index.scss';

function Loader({
  variant,
  size,
  color,
  style
}) {
  const childStyle = {};
  if (color) {
    if (variant === 'circle') childStyle.borderTopColor = color;
    if (variant === 'dots') childStyle.backgroundColor = color;
  }

  if (variant === 'dots') {
    return (
      <div style={style} className={c(s.dots, s[size])}>
        <div className={c(s.dotsChild, s[size])} style={childStyle} />
        <div className={c(s.dotsChild, s[size])} style={childStyle} />
        <div className={c(s.dotsChild, s[size])} style={childStyle} />
      </div>
    );
  }

  return (
    <div style={style} className={c(s.circle, s[size])}>
      <div className={s[size]} style={childStyle} />
      <div className={s[size]} style={childStyle} />
      <div className={s[size]} style={childStyle} />
      <div className={s[size]} style={childStyle} />
    </div>
  );

};

Loader.Guide = Guide;

Loader.defaultProps = {
  size: 'm',
  variant: 'circle',
  color: '#3155da'
};

Loader.propTypes = {
  variant: PropTypes.string,
  size: PropTypes.string,
  color: PropTypes.string
};

export default Loader;

// packages/vue/components/Loader/index.vue
<script>
  import Guide from './Guide';
  import s from '../../../common/Loader/index.scss';

  export default {
    Guide,
    name: 'Loader',
    props: {
      variant: { type: String, default: 'circle' },
      color: { type: String, default: '#3155da' },
      size: { type: String, default: 'm' }
    },
    data() {
      const childStyle = {};
      if (this.$props.variant === 'dots') childStyle.backgroundColor = this.$props.color;
      if (this.$props.variant === 'circle') childStyle.borderTopColor = this.$props.color;

      return { s, childStyle }
    }
  }
</script>

<template>
  <div
    v-if="variant === 'dots'"
    :class="[s.dots, s[size]]"
  >
    <div :class="[s.dotsChild, s[size]]" :style="childStyle" />
    <div :class="[s.dotsChild, s[size]]" :style="childStyle" />
    <div :class="[s.dotsChild, s[size]]" :style="childStyle" />
  </div>

  <div
    v-else
    :class="[s.circle, s[size]]"
  >
    <div :class="s[size]" :style="childStyle" />
    <div :class="s[size]" :style="childStyle" />
    <div :class="s[size]" :style="childStyle" />
    <div :class="s[size]" :style="childStyle" />
  </div>
</template>
