// packages/react/components/Menu/components/Item.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import c from 'clsx';
import s from '../../../../common/Menu/index.scss';

export default function MenuItem ({
  children,
  style,
  className,
  active,
  value,
  icon,
  exact,
  to,
  onClick,
  _nested,
  _onChange
}) {
  const _style = { paddingLeft: 22 * _nested, ...style };
  const classes = c(s.menuItem, className, {
    [s.menuItemActive]: (value && active === value) || active === true
  });

  if (to) {
    return (
      <Link
        to={to}
        exact={(!!exact).toString()}
        style={_style}
        className={classes}
      >
        {children}
      </Link>
    )
  }

  return (
    <div
      style={_style}
      className={classes}
      onClick={()=> _onChange(value, children)}
    >
      {children}
    </div>
  );
}

// packages/svelte/components/Menu/components/Item.svelte
<script>
  import { getContext } from 'svelte';
  import { Link } from 'svelte-routing';
  import c from 'clsx';
  import s from '../../../../common/Menu/index.scss';

  export let value = '';
  export let to = '';

  let active = '';
  const activeStore = getContext('active');
  activeStore.subscribe(v => active = v);
</script>

{#if !to}
  <div
    class={c(s.menuItem, {
      [s.menuItemActive]: active === value
    })}
    on:click={()=> activeStore.set(value)}
  >
    <slot />
  </div>
{/if}

{#if to}
  <Link
    to={to}
    class={c(s.menuItem, {
      [s.menuItemActive]: active === to
    })}
    on:click={()=> activeStore.set(to)}
  >
    <slot />
  </Link>
{/if}
