// packages/vue/components/Menu/components/Item.vue
<script>
  import s from '../../../../common/Menu/index.scss';

  export default {
    name: 'l-menu-item',
    props: {
      to: String,
      active: Boolean,
      value: String
    },
    data() {
      return { s }
    }
  }
</script>

<template>
  <router-link
    v-if="!!to"
    :to="to"
    :class="[s.menuItem, { [s.menuItemActive]: active === true }]"
  >
    <slot />
  </router-link>

  <div
    v-else
    :class="[s.menuItem, {
      [s.menuItemActive]: (value && $parent.active === value) || (active === true)
    }]"
    v-on:click="$parent.active = value"
  >
    <slot />
  </div>
</template>

// packages/svelte/components/Menu/components/Item.svelte
<script>
  import { getContext } from 'svelte';
  import { Link } from 'svelte-routing';
  import c from 'clsx';
  import s from '../../../../common/Menu/index.scss';

  export let value = '';
  export let to = '';

  let active = '';
  const activeStore = getContext('active');
  activeStore.subscribe(v => active = v);
</script>

{#if !to}
  <div
    class={c(s.menuItem, {
      [s.menuItemActive]: active === value
    })}
    on:click={()=> activeStore.set(value)}
  >
    <slot />
  </div>
{/if}

{#if to}
  <Link
    to={to}
    class={c(s.menuItem, {
      [s.menuItemActive]: active === to
    })}
    on:click={()=> activeStore.set(to)}
  >
    <slot />
  </Link>
{/if}
