// packages/svelte/components/Drawer/Guide.svelte
<script>
  import { Code, InlineCode as I } from '../../helpers';
  import Drawer from './Drawer.svelte';
  import Button from '../Button';

  let visible = false;
</script>

<h1>Drawer</h1>
<Drawer
  visible={visible}
  onDismiss={()=> visible = false}
>Контент</Drawer>
<Button on:click={()=> visible = true}>Открыть</Button>

// packages/react/components/Drawer/Guide.jsx
import React, { useState } from 'react'
import { Code, InlineCode as I } from '../../helpers';
import Drawer from './'
import Button from '../Button'

export default function DrawerGuide () {

  return (
    <>
      <h1>Drawer</h1>
      <Code v="import { Drawer } from 'loft-ui'" />

      <h2>Пример</h2>
      <Example />
    </>
  )

}

function Example () {
  const [visible, setVisible] = useState(false);

  return (
    <>
      <Button onClick={()=> setVisible(true)}>Открыть</Button>
      <Drawer
        visible={visible}
        onDismiss={()=> setVisible(false)}
      >
        Content
      </Drawer>
    </>
  )
}
