// packages/vue/components/Drawer/Guide.vue
<script>
  import { Code, InlineCode as I } from '../../helpers';

  export default {
    components: {
      I, Code,
      'l-drawer': () => import('./'),
      'l-button': () => import('../Button')
    },
    data: ()=> ({
      visible: false
    })
  }
</script>

<template>
  <div>
    <h1>Drawer</h1>
    <Code v="import { l-drawer } from 'loft-ui';" />

    <h2>Простой пример</h2>
    <Code v="
      data: ()=> ({ visible: false }),
      template: `
        <l-drawer
          :visible='visible'
          :onDismiss='()=> visible = false'
        >Content</l-drawer>
        <l-button @click.native='visible = !visible'>
          Открыть
        </l-button>
      `
    " lang="html" />
    <l-drawer
      :visible="visible"
      :onDismiss="()=> visible = false"
    >Контент</l-drawer>
    <l-button @click.native="visible = !visible">
      Открыть
    </l-button>
  </div>
</template>

// packages/react/components/Drawer/Guide.jsx
import React, { useState } from 'react'
import { Code, InlineCode as I } from '../../helpers';
import Drawer from './'
import Button from '../Button'

export default function DrawerGuide () {

  return (
    <>
      <h1>Drawer</h1>
      <Code v="import { Drawer } from 'loft-ui';" />

      <h2>Простой пример</h2>
      <Example />
    </>
  )

}

function Example () {
  const [visible, setVisible] = useState(false);

  return (
    <>
      <Button onClick={()=> setVisible(true)}>Открыть</Button>
      <Drawer
        visible={visible}
        onDismiss={()=> setVisible(false)}
      >
        Content
      </Drawer>
    </>
  )
}
