// packages/vue/components/Drawer/index.vue
<script>
  import Guide from './Guide';

  export default {
    Guide,
    name: 'l-drawer',
    components: {
      'l-drawer-fixed': () => import('./variants/Fixed')
      //'l-drawer-static': () => import('./variants/Static')
    },
    props: {
      variant: { type: String, default: 'fixed' },
      visible: { type: Boolean, default: false },
      onDismiss: { type: Function }
    }
  }
</script>

<template>
  <l-drawer-fixed
    :visible="visible"
    :onDismiss="onDismiss"
  >
    <slot />
  </l-drawer-fixed>
</template>

// packages/react/components/Drawer/index.jsx
import React, { useRef, useState } from 'react';
import DrawerFixed from './variants/Fixed';
import DrawerStatic from './variants/Static';
import Guide from './Guide';

function Drawer ({
  children,
  style,
  visible,
  position = 'left',
  variant = 'fixed',
  onDismiss
}) {
  if (variant === 'fixed') {
    return (
      <DrawerFixed
        visible={visible}
        position={position}
        onDismiss={onDismiss}
      >{children}</DrawerFixed>
    );
  }

  if (variant === 'static') {
    return (
      <DrawerStatic
        style={style}
        visible={visible}
      >{children}</DrawerStatic>
    );
  }
}

Drawer.Guide = Guide;

export default Drawer;
