// packages/react/components/Menu/index.jsx
import React, { useRef, useEffect } from 'react';
import PropTypes from 'prop-types';
import Guide from './Guide';
import { c } from '../../helpers';
import s from '../../../common/Menu/index.scss';

function Menu ({
  children,
  className,
  variant,
  active,
  onChange,
}) {
  children = React.Children.toArray(children).map(child=> {
    return React.cloneElement(child, {
      active,
      _nested: 1,
      _onChange: (value, label)=> onChange(value, label)
    });
  });

  return (
    <div className={s.menu}>
      {children}
    </div>
  );
}

Menu.Guide = Guide;

Menu.Item = function MenuItem ({
  children,
  className,
  active,
  value,
  icon,
  to,
  onClick,
  _nested,
  _onChange
}) {

  return (
    <div
      onClick={()=> _onChange(value)}
      className={c(s.menuItem, {
        [s.menuItemActive]: active === value
      })}
    >
      {children}
    </div>
  );

}

Menu.defaultProps = {
  variant: 'horizontal'
};

Menu.propTypes = {
  variant: PropTypes.oneOf(['horizontal', 'vertical'])
};

export default Menu;

// packages/vue/components/Menu/index.vue
<script>
  import Guide from './Guide';
  import s from '../../../common/Menu/index.scss';

  export default {
    Guide,
    name: 'l-menu',
    props: {
      variant: { type: String, default: 'horizontal' },
      active: { type: String, default: '' },
      _onChange: { type: Function }
    },
    provide: function() {
      const store = {}

      Object.defineProperty(store, 'active', {
        enumerable: true,
        get: () => this.active
      })

      return {
        store,
        onChange: this.onChange
      }
    },
    methods: {
      onChange(value, label) {
        this._onChange
          ? this._onChange(value, label)
          : this.$emit('change', value, label);
      }
    },
    data: ()=> ({ s })
  }
</script>

<template>
  <div :class="[s.menu, s[variant]]">
    <slot />
  </div>
</template>
