// packages/svelte/components/Menu/Menu.svelte
<script>
  import { setContext } from 'svelte';
  import { writable } from 'svelte/store';
  import c from 'clsx';
  import s from '../../../common/Menu/index.scss';

  export let style = '';
  export let variant = 'horizontal';
  export let active = '';

  setContext('active', writable(active));
</script>

<div
  style={style}
  class={c(s.menu, s[variant], $$props.class)}
>
  <slot />
</div>

// packages/vue/components/Menu/index.vue
<script>
  import Guide from './Guide';
  import s from '../../../common/Menu/index.scss';

  export default {
    Guide,
    name: 'l-menu',
    props: {
      variant: { type: String, default: 'horizontal' },
      active: { type: String, default: '' }
    },
    data() {
      return { s }
    }
  }
</script>

<template>
  <div :class="[s.menu, s[variant]]">
    <slot />
  </div>
</template>
