// packages/svelte/components/Rating/Rating.svelte
<script>
  import c from 'clsx';
  import s from '../../../common/Rating/index.scss';

  let activeIndex = -1;
  let hoverIndex = -1;

  const starts = new Array(5).fill(true)
</script>

<div
  class={s.loftRating}
  on:mouseleave={()=> hoverIndex = -1}
>
  {#each starts as _, index}
    <div
      class={c(s.loftRatingItem, {
        [s.loftRatingItemLastHover]: index === hoverIndex,
        [s.loftRatingItemHover]: index <= hoverIndex,
        [s.loftRatingItemActive]: index <= activeIndex
      })}
      on:mousemove={()=> hoverIndex = index}
      on:click={()=> activeIndex = index}
    />
  {/each}
</div>

// packages/vue/components/Rating/index.vue
<script>
  import Guide from './Guide';
  import s from '../../../common/Rating/index.scss';

  export default {
    Guide,
    name: 'l-rating',
    props: {
      value: { type: Number, default: 50 },
      total: { type: Number, default: 100 },
      count: { type: Number, default: 5 }
    },
    data() {
      return {
        s,
        hoverIndex: -1,
        activeIndex: -1
      }
    }
  }
</script>

<template>
  <div
    :class="s.loftRating"
    @mouseleave="hoverIndex = -1"
  >
    <div
      v-for="_, index in new Array(5).fill(true)"
      :class="[s.loftRatingItem, {
        [s.loftRatingItemHover]: index <= hoverIndex,
        [s.loftRatingItemActive]: index <= activeIndex
      }]"
      @mousemove="hoverIndex = index"
      v-on:click="activeIndex = index"
    />
  </div>
</template>
