// packages/vue/components/Dropdown/Guide.vue
<script>
  import { Code, InlineCode as I } from '../../helpers';

  export default {
    components: {
      I, Code,
      'l-dropdown': () => import('./')
    }
  }
</script>

<template>
  <div>
    <h1>Dropdown</h1>
    <Code v="import { l-dropdown } from 'loft-ui';" />

    <h2>Простой пример</h2>
  </div>
</template>

// packages/svelte/components/Pagination/Guide.svelte
<script>
  import { Code, InlineCode as I } from '../../helpers';
  import Pagination from './Pagination';

  let page = 3;
</script>

<h1>Pagination</h1>
<Code v={`import { Pagination } from 'loft-ui';`} lang="js" />

<h2>Простой пример</h2>
<Code v={`
  <script>
    let page = 3;
  </script>

  <Pagination
    count={10}
    page={page}
  />
`} />
<Pagination
  count={10}
  page={page}
/>
