// packages/svelte/components/Tooltip/Guide.svelte
<script>
  import { Code, InlineCode as I } from '../../helpers';
  import Tooltip from './Tooltip.svelte';
  import Example from './Example.svelte';

  let visible = false;
</script>

<h1>Tooltip</h1>
<Tooltip
  content={Example}
>
  <div style="
    width: 36px;
    height: 36px;
    background-color: #f4f5f7;
    border-radius: 60px;
  " />
</Tooltip>

// packages/react/components/Tooltip/Guide.jsx
import React from 'react';
import { Code, InlineCode as I } from '../../helpers';
import Tooltip from './';

export default function TooltipGuide () {

  const exampleContent = (
    <div>Content</div>
  );

  return (
    <>
      <h1>Tooltip</h1>
      <Code v="import { Popover } from 'loft-ui';" />

      <h2>Простой пример</h2>
      <Tooltip content={exampleContent}>
        <div style={{
          width: '36px',
          height: '36px',
          backgroundColor: '#f4f5f7',
          borderRadius: 60
        }} />
      </Tooltip>
    </>
  );
}
