// packages/vue/components/Breadcrumbs/index.vue
<script>
  import Guide from './Guide';
  import s from '../../../common/Breadcrumbs/index.scss';

  export default {
    Guide,
    name: 'l-breadcrumbs',
    components: {
      'l-breadcrumbs-separator': () => import('./Separator')
    },
    props: {
      data: { type: Array, default: [] },
      separator: { type: Object }
    },
    data: ()=> ({ s })
  }
</script>

<template>
  <div :class="s.breadcrumbs">
    <template v-for="item, index in data">
      <div
        v-if="index + 1 === data.length"
        :class="[s.breadcrumbsTitle, s.breadcrumbsTitleActive]"
      >{{item.title}}</div>

      <router-link
        :to="item.link"
        v-if="index + 1 !== data.length"
        :class="s.breadcrumbsTitle"
      >{{item.title}}</router-link>

      <l-breadcrumbs-separator
        v-if="index + 1 !== data.length"
        :separator="separator"
      />
    </template>
  </div>
</template>

// packages/svelte/components/Breadcrumbs/Breadcrumbs.svelte
<script>
  import { Link } from 'svelte-routing';
  import Separator from './Separator/index.svelte'
  import c from 'clsx';
  import s from '../../../common/Breadcrumbs/index.scss';

  export let data = []
</script>

<div class={s.breadcrumbs}>
  {#each data as item, index}
    {#if index + 1 === data.length}
      <div class={c([s.breadcrumbsTitle, s.breadcrumbsTitleActive])}>
        {item.title}
      </div>
    {/if}

    {#if index + 1 !== data.length}
      <Link
        to={item.link}
        class={s.breadcrumbsTitle}
      >{item.title}</Link>
    {/if}
    
    {#if index + 1 !== data.length}
      <Separator />
    {/if}
  {/each}
</div>
