// packages/react/components/Popover/Guide.jsx
import React, { useState } from 'react';
import { Code, InlineCode as I } from '../../helpers';
import Popover from './';
import Button from '../Button';
import c from 'clsx';
import s from '../../../common/Popover/guide.scss';

export default function PopoverGuide () {
  const [example, setExample] = useState(false);

  return (
    <>
      <h1>Popover</h1>
      <Code v="import { Popover } from 'loft-ui';" />

      <h2>Простой пример</h2>
      <Popover
        visible={example}
        onDismiss={()=> setExample(false)}
        className={s.example}
        content={(
          <>
            <div className={s.exampleTitle}>Notifications</div>
            <div className={s.exampleList}>
              <div className={s.exampleItem}>
                <div className={s.exampleAvatar} />
                <div className={s.exampleItemText}>
                  <div className={s.exampleItemTitle}>Уведомление</div>
                  <div className={s.exampleItemDesc}>Задача организации, в особенно...</div>
                </div>
              </div>
              <div className={s.exampleItem}>
                <div className={s.exampleAvatar} />
                <div className={s.exampleItemText}>
                  <div className={s.exampleItemTitle}>Уведомление</div>
                  <div className={s.exampleItemDesc}>Задача организации, в особенно...</div>
                </div>
              </div>
              <div className={s.exampleItem}>
                <div className={s.exampleAvatar} />
                <div className={s.exampleItemText}>
                  <div className={s.exampleItemTitle}>Уведомление</div>
                  <div className={s.exampleItemDesc}>Задача организации, в особенно...</div>
                </div>
              </div>
            </div>
            <div className={s.exampleActionCase}>
              <Button className={s.exampleAction}>
                Read all notifications
              </Button>
            </div>
          </>
        )}
      >
        <div
          className={c(s.exampleIcon, { [s.exampleIconActive]: example })}
          onClick={()=> setExample(!example)}
        />
      </Popover>
    </>
  )

}

// packages/vue/components/Popover/Guide.vue
<script>
  import { Code, InlineCode as I } from '../../helpers';
  import s from '../../../common/Popover/guide.scss';

  export default {
    components: {
      I, Code,
      'l-popover': ()=> import('./')
    },
    data: ()=> ({
      s,
      example: false
    })
  }
</script>

<template>
  <div>
    <h1>Popover</h1>
    <Code v="import { l-popover } from 'loft-ui';" />

    <h2>Простой пример</h2>
    <l-popover
      :className="s.example"
      :visible="example"
      :content="{
        components: {
          'l-button': ()=> import('../Button')
        },
        data: ()=> ({ s }),
        template: `
          <div>
            <div :class='s.exampleTitle'>Notifications</div>
            <div :class='s.exampleList'>
              <div :class='s.exampleItem'>
                <div :class='s.exampleAvatar' />
                <div :class='s.exampleItemText'>
                  <div :class='s.exampleItemTitle'>Уведомление</div>
                  <div :class='s.exampleItemDesc'>Задача организации, в особенно...</div>
                </div>
              </div>
              <div :class='s.exampleItem'>
                <div :class='s.exampleAvatar' />
                <div :class='s.exampleItemText'>
                  <div :class='s.exampleItemTitle'>Уведомление</div>
                  <div :class='s.exampleItemDesc'>Задача организации, в особенно...</div>
                </div>
              </div>
              <div :class='s.exampleItem'>
                <div :class='s.exampleAvatar' />
                <div :class='s.exampleItemText'>
                  <div :class='s.exampleItemTitle'>Уведомление</div>
                  <div :class='s.exampleItemDesc'>Задача организации, в особенно...</div>
                </div>
              </div>
            </div>
            <div :class='s.exampleActionCase'>
              <l-button :class='s.exampleAction'>
                Read all notifications
              </l-button>
            </div>
          </div>
        `
      }"
    >
      <div
        :class="[s.exampleIcon, { [s.exampleIconActive]: example }]"
        @click="example = !example"
      />
    </l-popover>
  </div>
</template>
