// packages/react/components/Loader/index.jsx
import React from 'react';
import PropTypes from 'prop-types';
import Guide from './Guide';
import c from 'clsx';
import s from '../../../common/Loader/index.scss';

function Loader({
  variant,
  size,
  color,
  style
}) {
  const childStyle = {};
  if (color) {
    if (variant === 'circle') childStyle.borderTopColor = color;
    if (variant === 'dots') childStyle.backgroundColor = color;
  }

  if (variant === 'dots') {
    return (
      <div style={style} className={c(s.dots, s[size])}>
        <div className={c(s.dotsChild, s[size])} style={childStyle} />
        <div className={c(s.dotsChild, s[size])} style={childStyle} />
        <div className={c(s.dotsChild, s[size])} style={childStyle} />
      </div>
    );
  }

  return (
    <div style={style} className={c(s.circle, s[size])}>
      <div className={s[size]} style={childStyle} />
      <div className={s[size]} style={childStyle} />
      <div className={s[size]} style={childStyle} />
      <div className={s[size]} style={childStyle} />
    </div>
  );

};

Loader.Guide = Guide;

Loader.defaultProps = {
  size: 'm',
  variant: 'circle',
  color: '#3155da'
};

Loader.propTypes = {
  variant: PropTypes.string,
  size: PropTypes.string,
  color: PropTypes.string
};

export default Loader;

// packages/svelte/components/Loader/Loader.svelte
<script>
  import c from 'clsx';
  import s from '../../../common/Loader/index.scss';

  export let style = '';
  export let variant = 'circle';
  export let size = 'm';
  export let color = '#3155da';

  let childStyle = '';
  if (color) {
    if (variant === 'circle') childStyle = 'border-top-color:' + color;
    if (variant === 'dots') childStyle = 'background-color:' + color;
  }
</script>

{#if variant === 'circle'}
  <div class={c(s.circle, s[size])} style={style}>
    <div class={s[size]} style={childStyle} />
    <div class={s[size]} style={childStyle} />
    <div class={s[size]} style={childStyle} />
    <div class={s[size]} style={childStyle} />
  </div>
{:else}
  <div class={c(s.dots, s[size])} style={style}>
    <div class={c(s.dotsChild, s[size])} style={childStyle} />
    <div class={c(s.dotsChild, s[size])} style={childStyle} />
    <div class={c(s.dotsChild, s[size])} style={childStyle} />
  </div>
{/if}
