// packages/svelte/components/Pagination/Guide.svelte
<script>
  import { Code, InlineCode as I } from '../../helpers';
  import Pagination from './Pagination';

  let page = 3;
</script>

<h1>Pagination</h1>
<Code v={`import { Pagination } from 'loft-ui';`} lang="js" />

<h2>Простой пример</h2>
<Code v={`
  <script>
    let page = 3;
  </script>

  <Pagination
    count={10}
    page={page}
  />
`} />
<Pagination
  count={10}
  page={page}
/>

// packages/react/components/Pagination/Guide.jsx
import React, { useState } from 'react';
import { Code, InlineCode as I } from '../../helpers';
import Pagination from './';

export default function PaginationGuide () {

  return (
    <>
      <h1>Pagination</h1>
      <p>Компонент для переключения между частями контента</p>
      <Code v="import { Pagination } from 'loft-ui'" />

      <h2>Простой пример</h2>
      <Code v={`
        const [page, setPage] = useState('');

        return (
          <Pagination
            count={10}
            page={page}
            onChange={v=> setPage(v)}
          />
        )
      `} />
      <Example />
    </>
  )

}

function Example () {
  const [page, setPage] = useState(3);

  return (
    <Pagination
      count={10}
      page={page}
      onChange={v=> setPage(v)}
    />
  )
}
