// packages/vue/components/Pagination/index.vue
<script>
  import Guide from './Guide';
  import s from './index.scss';

  export default {
    Guide,
    name: 'Pagination',
    props: {
      count: { type: Number, default: 5 },
      page: { type: Number, default: 1 },
      onChange: Function
    },
    computed: {
      numbersPage() {
        const { page, count } = this;
        const countShow = (count < 5) ? count : 5;
        const startIndex = page - 2;
        const arr = [];

        for (let index = startIndex; arr.length < countShow; index++) {
          if (index > count) {
            arr.unshift(arr[0] - 1);
            continue;
          }
          if (index > 0) {
            arr.push(index);
          }
        }

        return arr;
      }
    },
    data: ()=> ({ s })
  }
</script>

<template>
  <div :class="s.pagination">
    <div :class="[s.paginationFastLink, { [s.paginationHide]: page === 1 }]">
      <div
        :class="s.arrow"
        v-if="page !== 1"
        v-on:click="onChange(page - 1)"
      >{{'<'}}</div>
    </div>

    <div :class="s.list">
      <div
        :class="s.item"
        v-if="numbersPage[0] !== 1"
        v-on:click="onChange(1)"
      >1</div>
      <div
        :class="[s.item, s.itemPure]"
        v-if="numbersPage[0] !== 1"
      >..</div>

      <div
        :class="[s.item, { [s.active]: page === number }]"
        v-for="number in numbersPage"
        v-on:click="onChange(number)"
      >{{number}}</div>

      <div
        :class="[s.item, s.itemPure]"
        v-if="numbersPage[numbersPage.length - 1] !== count"
      >..</div>
      <div
        :class="s.item"
        v-if="numbersPage[numbersPage.length - 1] !== count"
        v-on:click="onChange(count)"
      >{{count}}</div>
    </div>

    <div :class="[s.paginationFastLink, { [s.paginationHide]: page === count }]">
      <div
        :class="s.arrow"
        v-if="page !== count"
        v-on:click="onChange(page + 1)"
      >{{'>'}}</div>
    </div>
  </div>
</template>

// packages/react/components/Pagination/index.js
import React from 'react';
import { c } from '../../helpers';
import guide from './index.mdx';
import s from './index.scss';

function Pagination({
  className,
  style,
  count = 5,
  page = 1,
  onChange
}) {
  if (!onChange) return null;

  const getArrayPagination = (count, page)=> {
    const countShow = (count < 5) ? count : 5;
    const startIndex = page - 2;
    const arr = [];

    for (let index = startIndex; arr.length < countShow; index++) {
      if (index > count) {
        arr.unshift(arr[0] - 1);
        continue;
      }
      if (index > 0) {
        arr.push(index);
      }
    }

    return arr;
  };

  const numbersPage = getArrayPagination(count, page);
  return count > 1 && (
    <div
      className={c(s.pagination, className)}
      style={style}
    >
      <div className={c(s.paginationFastLink, { [s.paginationHide]: page === 1 })}>
        {page !== 1 && <div className={s.arrow} onClick={()=> onChange(page - 1)}>{'<'}</div>}
      </div>

      <div className={s.list}>
        {
          numbersPage[0] !== 1 &&
          <>
            <div className={s.item} onClick={()=> onChange(1)}>1</div>
            <div className={c(s.item, s.itemPure)}>..</div>
          </>
        }
        {
          numbersPage.map((number, index)=> (
            <div
              className={c(s.item, { [s.active]: page === number })}
              onClick={()=> onChange(number)}
              key={index}
            >{number}</div>
          ))
        }
        {
          numbersPage[numbersPage.length - 1] !== count &&
          <>
            <div className={c(s.item, s.itemPure)}>..</div>
            <div className={s.item} onClick={()=> onChange(count)}>{count}</div>
          </>
        }
      </div>

      <div className={c(s.paginationFastLink, { [s.paginationHide]: page === count })}>
        {
          page !== count &&
          <div className={s.arrow} onClick={()=> onChange(page + 1)}>{'>'}</div>
        }
      </div>
    </div>
  );
};

Pagination.guide = guide;

export default Pagination;
