// packages/vue/components/Rating/Guide.vue
<script>
  import { Code, InlineCode as I } from '../../helpers';

  export default {
    components: {
      I, Code,
      'l-rating': () => import('./')
    }
  }
</script>

<template>
  <div>
    <h1>Rating</h1>
    <Code v="import { l-rating } from 'loft-ui';" />

    <h2>Простой пример</h2>
    <l-rating />
  </div>
</template>

// packages/svelte/components/Switch/Guide.svelte
<script>
  import { Code, InlineCode as I } from '../../helpers';
  import Switch from './Switch';

  let selected = false;
</script>

<h1>Switch</h1>
<Code v={`import { Switch } from 'loft-ui';`} lang="js" />

<h2>Простой пример</h2>
<Switch
  selected={selected}
  on:click={()=> selected = !selected}
/>
