// packages/react/components/Switch/index.jsx
import React from 'react';
// import PropTypes from 'prop-types';
import Guide from './Guide';
import c from 'clsx';
import s from '../../../common/Switch/index.scss';

function Switch({
  selected,
  style,
  className,
  // color,
  onClick
}) {
  return (
    <div
      className={c(s.switch, { [s.active]: selected })}
      style={style}
      onClick={onClick}
    >
      <div className={c(s.circle, className)} />
    </div>
  );
};

Switch.Guide = Guide;

Switch.propTypes = {};

export default Switch;

// packages/svelte/components/Switch/Switch.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  import c from 'clsx';
  import s from '../../../common/Switch/index.scss';

  export let selected = false;

  const dispatch = createEventDispatcher();
</script>

<div
  class={c(s.switch, { [s.active]: selected })}
  on:click={()=> dispatch('click')}
>
  <div class={c(s.circle)} />
</div>
