// packages/vue/components/Avatar/index.vue
<script>
  import Guide from './Guide';
  import s from './index.scss';

  export default {
    Guide,
    name: 'Avatar',
    props: {
      size: { type: String, default: 'm' },
      shape: { type: String, default: 'circle' },
      src: String
    },
    data() {
      let style = '';
      if (this.$props.src) {
        style = `background-image: url(${this.$props.src})`;
      }

      return { s, style }
    }
  }
</script>

<template>
  <div
    :class="[s.avatar, s[size], s[shape]]"
    :style="style"
  />
</template>

// packages/react/components/Avatar/index.js
import React from 'react';
import PropTypes from 'prop-types';
import { c } from '../../helpers';
import guide from './index.mdx';
import s from './index.scss';

function Avatar({
  className,
  style,
  src,
  size,
  shape
}) {
  const _style = { ...style };
  if (src) _style.backgroundImage = `url(${src})`;

  return (
    <div
      className={c(s.avatar, s[size], s[shape], className)}
      style={_style}
    />
  );
};

Avatar.guide = guide;

Avatar.defaultProps = {
  style: {},
  src: '',
  size: 'm',
  shape: 'circle'
};

Avatar.propTypes = {
  className: PropTypes.string,
  src: PropTypes.string,
  size: PropTypes.string,
  shape: PropTypes.string
};

export default Avatar;
