// packages/vue/components/Dropdown/Guide.vue
<script>
  import { Code, InlineCode as I } from '../../helpers';

  export default {
    components: {
      I, Code,
      'l-dropdown': () => import('./')
    },
    data: ()=> ({
      example: ''
    })
  }
</script>

<template>
  <div>
    <h1>Dropdown</h1>
    <Code v="import { l-dropdown } from 'loft-ui';" />

    <h2>Простой пример</h2>
    <div style="width: 280px;">
      <l-dropdown
        :value="example"
        :data="[
          { value: 'java', label: 'Java' },
          { value: 'js', label: 'JavaScript' },
          { value: 'cpp', label: 'C++' }
        ]"
        @change="v=> example = v"
      />
    </div>
  </div>
</template>

// packages/react/components/Dropdown/Guide.jsx
import React, { useState } from 'react';
import { Code } from '../../helpers';
import Dropdown from './';

export default function DropdownGuide() {
  const [example, setExample] = useState('');

  return (
    <>
      <h1>Dropdown</h1>
      <p>Выпадающее меню - это навигация, для выбора значения</p>
      <Code v="import { Dropdown } from 'loft-ui';" />

      <h2>Простой пример</h2>
      <Code v={`
        const [value, setValue] = useState('');

        return (
          <Dropdown
            value={value}
            label='Language'
            data={[
              { value: 'java', label: 'Java' },
              { value: 'js', label: 'JavaScript' },
              { value: 'cpp', label: 'C++' }
            ]}
            onChange={v=> setValue(v)}
          />
        )
      `} />
      <div style={{ width: '280px' }}>
        <Dropdown
          value={example}
          label='Language'
          data={[
            { value: 'java', label: 'Java' },
            { value: 'js', label: 'JavaScript' },
            { value: 'cpp', label: 'C++' }
          ]}
          onChange={v=> setExample(v)}
        />
      </div>
    </>
  );
}
