// packages/react/components/Input/index.jsx
import React, { useRef, useState } from 'react';
import InputMask from 'react-input-mask';
import Guide from './Guide';
import c from 'clsx';
import s from '../../../common/Input/index.scss';

const InputCommon = props=> <input {...props} />;

function Input({
  variant = 'line',
  label,
  type,
  value,
  mask,
  style,
  className,
  classLabel,
  classInput,
  classFieldset,
  onFocus,
  onBlur,
  onChange,
  ...props
}) {
  const [focus, setFocus] = useState(false);

  const _props = {
    type,
    value,
    onChange: e=> onChange && onChange(e.target.value),
    onFocus: ()=> {
      onFocus && onFocus();
      setFocus(true);
    },
    onBlur: ()=> {
      onBlur && onBlur();
      setFocus(false);
    },
    ...props,
    className: c(s.input, classInput),
    autocomplete: 'new-password'
  };

  if (mask) {
    _props.mask = mask;
    _props.maskChar = null;
  }

  const Component = mask ? InputMask : InputCommon;

  if (variant === 'outline') {
    return (
      <div
        style={style}
        className={c(s.inputOutline, className, {
          [s.inputValue]: !!value,
          [s.inputFocus]: focus
        })}
      >
        <fieldset className={c(s.inputOutlineFieldset, classFieldset)}>
          <legend className={s.inputLegend}>{label}</legend>
        </fieldset>
        <label className={s.inputLabel}>{label}</label>
        <Component {..._props} />
      </div>
    );
  }

  return (
    <div
      style={style}
      className={c(s.inputLine, className, {
        [s.inputValue]: !!value,
        [s.inputFocus]: focus
      })}
    >
      <label className={c(s.inputLabel, classLabel)}>
        {label}
      </label>
      <Component {..._props} />
    </div>
  );
};

Input.Guide = Guide;

export default Input;

// packages/svelte/components/Input/Input.svelte
<script>
  import c from 'clsx';
  import s from '../../../common/Input/index.scss';

  export let variant = 'line';
  export let label = '';
  export let type;
  export let value = '';
  export let style;
  // export let className;
  export let classLabel;
  export let classInput;
  export let onFocus;
  export let onBlur;
  export let onChange;

  let focus = false;
  let refInput;

  function _onFocus () {
    onFocus && onFocus();
    focus = true;
  }

  function _onBlur () {
    onBlur && onBlur();
    focus = false;
  }
</script>

{#if variant === 'line'}
<div
  bind:this={refInput}
  style={style}
  class={c(s.inputLine, {
    [s.inputValue]: !!value,
    [s.inputFocus]: focus
  })}
>
  <label class={c(s.inputLabel, classLabel)}>
    {label}
  </label>

  <input
    type={type}
    value={value}
    class={c(s.input, classInput)}
    on:focus={_onFocus}
    on:blur={_onBlur}
    on:change={e=> onChange && onChange(e.target.value)}
  />
</div>
{/if}

{#if variant === 'outline'}
  <div
    bind:this={refInput}
    class={c(s.inputOutline, {
      [s.inputValue]: !!value,
      [s.inputFocus]: focus
    })}
  >
    <fieldset class={s.inputOutlineFieldset}>
      <legend class={s.inputLegend}>{label}</legend>
    </fieldset>
    <label class={s.inputLabel}>{label}</label>
    <input
      type={type}
      value={value}
      class={s.input}
      on:focus={_onFocus}
      on:blur={_onBlur}
      on:change={e=> onChange && onChange(e.target.value)}
    />
  </div>
{/if}
