// packages/react/components/Switch/index.jsx
import React from 'react';
// import PropTypes from 'prop-types';
import Guide from './Guide';
import c from 'clsx';
import s from '../../../common/Switch/index.scss';

function Switch({
  selected,
  style,
  className,
  // color,
  onClick
}) {
  return (
    <div
      className={c(s.switch, { [s.active]: selected })}
      style={style}
      onClick={onClick}
    >
      <div className={c(s.circle, className)} />
    </div>
  );
};

Switch.Guide = Guide;

Switch.propTypes = {};

export default Switch;

// packages/vue/components/Switch/index.vue
<script>
  import Guide from './Guide';
  import s from '../../../common/Switch/index.scss';

  export default {
    Guide,
    name: 'l-switch',
    props: {
      selected: { type: Boolean, default: false }
    },
    data() {
      return { s }
    }
  }
</script>

<template>
  <div :class="[s.switch, { [s.active]: selected }]">
    <div :class="s.circle" />
  </div>
</template>
