// packages/svelte/components/Avatar/Avatar.svelte
<script>
  import c from 'clsx';
  import s from '../../../common/Avatar/index.scss';

  export let style = '';
  export let src = '';
  export let size = 'm';
  export let shape = 'circle';

  if (src) style += `background-image: url(${src});`;
</script>

<div
  class={c(s.avatar, s[size], s[shape], $$props.class)}
  style={style}
/>

// packages/vue/components/Avatar/index.vue
<script>
  import Guide from './Guide';
  import s from '../../../common/Avatar/index.scss';

  export default {
    Guide,
    name: 'Avatar',
    props: {
      size: { type: String, default: 'm' },
      shape: { type: String, default: 'circle' },
      src: String
    },
    data() {
      let style = '';
      if (this.$props.src) {
        style = `background-image: url(${this.$props.src})`;
      }

      return { s, style }
    }
  }
</script>

<template>
  <div
    :class="[s.avatar, s[size], s[shape]]"
    :style="style"
  />
</template>
