// packages/react/components/Dropdown/index.jsx
import React, { useState } from 'react';
import Menu from '../Menu';
import Input from '../Input';
import Popover from '../Popover';
import Guide from './Guide';
import s from '../../../common/Dropdown/index.scss';
import c from 'clsx';

function Dropdown({
  label,
  data = [],
  value,
  onChange
}) {
  const [activeLabel, setActiveLabel] = useState('');
  const [visible, setVisible] = useState(false);

  function _onChange(value, label) {
    setActiveLabel(label);
    setVisible(false);
    onChange(value);
  }

  const content = (
    <Menu
      variant="vertical"
      active={value}
      onChange={_onChange}
    >
      {data.map(item=> (
        <Menu.Item value={item.value}>{item.label}</Menu.Item>
      ))}
    </Menu>
  );

  return (
    <Popover
      visible={visible}
      content={content}
      hasWidthCaption={true}
      className={s.content}
      onDismiss={()=> setVisible(false)}
    >
      <div
        className={c(s.dropdownCaption, {
          [s.dropdownActive]: visible,
          [s.dropdownSelect]: !!value
        })}
      >
        <div
          className={s.dropdownHandler}
          onClick={()=> setVisible(!visible)}
        />

        <Input
          variant="outline"
          label={label || 'Select value'}
          classFieldset={c({ [s.dropdownFocus]: visible })}
          value={activeLabel}
        />

        <div className={s.dropdownIcon}>
          <div className={s.line} />
          <div className={s.line} />
        </div>
      </div>
    </Popover>
  );
}

Dropdown.Guide = Guide;

export default Dropdown;

// packages/svelte/components/Dropdown/Dropdown.svelte
<script>
  import Popover from '../Popover';
  import Input from '../Input';
  import List from './List';
  import c from 'clsx';
  import s from '../../../common/Dropdown/index.scss';

  export let label = 'Select value';
  export let data = [];
  export let value = '';

  let visible = false;
  let activeLabel = '';

  $: contentProps = { value, data }
</script>

<Popover
  visible={visible}
  content={List}
  contentProps={contentProps}
  class={s.content}
  hasWidthCaption={true}
>
  <div
    class={c([s.dropdownCaption, {
      [s.dropdownActive]: visible,
      [s.dropdownSelect]: !!value
    }])}
  >
    <div
      class={s.dropdownHandler}
      on:click={()=> visible = !visible}
    />

    <Input
      label={label}
      value={activeLabel}
      variant='outline'
    />

    <div class={s.dropdownIcon}>
      <div class={s.line} />
      <div class={s.line} />
    </div>
  </div>
</Popover>
