// storybook/src/react/Sidebar.jsx
import React from 'react';
import { NavLink } from 'react-router-dom';
import * as components from '@loft-ui/react';
import s from '../index.scss';

export default function Sidebar() {

  return (
    <div className={s.sidebar}>
      {
        Object.keys(components).map(key=> {
          return <NavLink
            exact
            key={key}
            className={s.sidebarItem}
            activeClassName={s.sidebarItemActive}
            to={'/react/' + key.toLowerCase()}
          >{key}</NavLink>;
        })
      }
    </div>
  );

}

// storybook/src/vue/Sidebar.vue
<script>
  import * as components from '@loft-ui/vue';
  import s from '../index.scss';

  export default {
    name: 'sidebar',
    data: () => ({ s, components })
  }
</script>

<template>
  <div :class="s.sidebar">
    <router-link
      :class="s.sidebarItem"
      :active-class="s.sidebarItemActive"
      :to="'/vue/' + component.name.toLowerCase()"
      v-for="component in components"
      :key="component.name"
    >
      {{ component.name }}
    </router-link>
  </div>
</template>
