// packages/vue/components/Collapse/index.vue
<script>
  import Guide from './Guide';
  import Velocity from 'velocity-animate';
  import s from '../../../common/Collapse/index.scss';

  export default {
    name: 'l-collapse',
    Guide,
    props: {
      visible: { type: Boolean, default: false }
    },
    methods: {
      enter(el, done) {
        Velocity(el, { height: 0 }, { duration: 0 });

        const toHeight = el.getBoundingClientRect().height;
        const openStyle = { height: toHeight + 'px' };
        Velocity(el, openStyle, {
          duration: 300,
          complete: heightAuto
        });

        function heightAuto () {
          el.style = 'height: auto';
          done();
        }
      },
      leave(el, done) {
        Velocity(el, { height: 0 }, {
          duration: 300,
          complete: done
        });
      }
    },
    data: ()=> ({
      s,
      style: ''
    })
  }
</script>

<template>
  <transition
    @enter="enter"
    @leave="leave"
    :css="false"
  >
    <div
      v-if="visible"
      :class="s.case"
      :style="style"
      ref="ref"
    >
      <slot />
    </div>
  </transition>
</template>

// packages/react/components/Collapse/index.jsx
import React, { useRef, useState } from 'react';
import { CSSTransition } from 'react-transition-group';
import Guide from './Guide';
import c from 'clsx';
import s from '../../../common/Collapse/index.scss';

function Collapse({ visible, children }) {
  const ref = useRef();
  const [toHeight, setToHeight] = useState(null);
  const [style, setStyle] = useState({});

  function onEnter() {
    setToHeight(ref.current.getBoundingClientRect().height);
    setStyle({ height: 0 });
  }

  function onExit() {
    setStyle({ height: ref.current.getBoundingClientRect().height + 'px' });
  }

  return (
    <CSSTransition
      in={visible}
      timeout={300}
      style={style}
      unmountOnExit
      className={c(s.case, s.animate)}
      onEnter={onEnter}
      onEntering={()=> setStyle({ height: toHeight + 'px' })}
      onEntered={()=> setStyle({ height: 'auto' })}
      onExit={onExit}
      onExiting={()=> setStyle({ height: 0 })}
      onExited={()=> setStyle({})}
    >
      <div ref={ref}>{children}</div>
    </CSSTransition>
  );
}

Collapse.Guide = Guide;

export default Collapse;
