// packages/svelte/components/Radio/Item.svelte
<script>
  import { getContext } from 'svelte';
  import c from 'clsx';
  import s from '../../../common/Radio/index.scss';

  export let value = '';

  let active = '';
  const activeStore = getContext('active');
  activeStore.subscribe(v => active = v);
</script>

<div
  class={c([s.radio, { [s.active]: active === value }])}
  on:click={()=> activeStore.set(value)}
>
  <div class={s.iconCase}>
    <div class={s.icon} />
  </div>
  <div class={s.label}>
    <slot />
  </div>
</div>

// packages/vue/components/Radio/Item.vue
<script>
  import Guide from './Guide';
  import s from '../../../common/Radio/index.scss';

  export default {
    Guide,
    name: 'l-radio-item',
    props: {
      value: { type: String }
    },
    data() {
      return { s }
    }
  }
</script>

<template>
  <div
    :class="[s.radio, { [s.active]: $parent.active === value }]"
    v-on:click="$parent.active = value"
  >
    <div :class="s.iconCase">
      <div :class="s.icon" />
    </div>
    <div :class="s.label">
      <slot />
    </div>
  </div>
</template>
