// storybook/src/vue/App.vue
<script>
  import VueRouter from 'vue-router';
  import Sidebar from './Sidebar';
  import * as components from '@loft-ui/vue';
  import s from '../index.scss';

  const router = new VueRouter({
    mode: 'history',
    routes: Object.keys(components).map(key => {
      return {
        path: `/vue/${key}`,
        component: components[key].Guide
      }
    })
  });

  export default {
    router,
    name: 'app',
    components: { Sidebar },
    data: () => ({ s })
  }
</script>

<template>
  <main>
    <Sidebar />
    <router-view class="root"></router-view>
  </main>
</template>

// storybook/src/react/App.jsx
import React from 'react';
import { Switch, Route } from 'react-router-dom';
import Sidebar from './components/Sidebar';
import * as components from '@loft-ui/react';
import s from '../index.scss';

// RouteMiddleware
const Routers = ()=> {
  return (
    <main>
      <Sidebar />
      <div className={s.root}>
        <Switch>
          {
            Object.keys(components).map(key=> {
              if (!components[key].guide) return null;
              return <Route
                exact
                key={key}
                path={`/react/${key}`}
                component={components[key].guide}
              />;
            })
          }
        </Switch>
      </div>
    </main>
  );
};

export default Routers;
