// storybook/src/svelte/App.svelte
<script>
  import { Router, Route } from 'svelte-routing';
  import Sidebar from './Sidebar';
  import * as components from '@loft-ui/svelte';

  let url = '';
</script>

<main>
  <Router url="{url}">
    <Sidebar />
    <div class="root">
      {#each Object.keys(components) as key}
        <Route
          path={'/svelte/' + key.toLowerCase()}
          component="{components[key].Guide}"
        />
      {/each}
    </div>
  </Router>
</main>

// storybook/src/react/App.jsx
import React from 'react';
import { Switch, Route } from 'react-router-dom';
import * as components from '@loft-ui/react';
import Sidebar from './Sidebar';

const Routers = ()=> {
  return (
    <main>
      <Sidebar />
      <div className="root">
        <Switch>
          {
            Object.keys(components).map(key=> {
              if (!components[key].Guide) return null;
              return <Route
                exact
                key={key}
                path={`/react/${key}`}
                component={components[key].Guide}
              />;
            })
          }
        </Switch>
      </div>
    </main>
  );
};

export default Routers;
