// storybook/src/react/Sidebar.jsx
import React from 'react';
import { NavLink, useLocation } from 'react-router-dom';
import { Menu } from '@loft-ui/react';
import * as components from '@loft-ui/react';
import s from '../index.scss';

export default function Sidebar() {
  const { pathname } = useLocation();

  return (
    <Menu
      variant='vertical'
      className={s.sidebar}
    >
      {
        Object.keys(components).map(key=> {
          return <Menu.Item
            key={key}
            exact
            active={'/react/' + key.toLowerCase() === pathname}
            to={'/react/' + key.toLowerCase()}
          >{key}</Menu.Item>;
        })
      }
    </Menu>
  );

}

// storybook/src/svelte/Sidebar.svelte
<script>
  import * as components from '@loft-ui/svelte';
  import { Menu } from '@loft-ui/svelte';
  import c from 'clsx';
  import s from '../index.scss';

  function getProps({ href, isPartiallyCurrent, isCurrent }) {
    const isActive = href === '/' ? isCurrent : isPartiallyCurrent || isCurrent;

    if (isActive) {
      return { class: c(s.sidebarItem, s.sidebarItemActive) };
    }

    return { class: s.sidebarItem };
  }
</script>

<Menu
  class={s.sidebar}
  active={window.location.pathname}
  variant='vertical'
>
  {#each Object.keys(components) as key}
    <Menu.Item to={'/svelte/' + key.toLowerCase()}>
      {key}
    </Menu.Item>
  {/each}
</Menu>
