// packages/svelte/components/Checkbox/Checkbox.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  import c from 'clsx';
  import s from '../../../common/Checkbox/index.scss';

  export let selected = false;

  const dispatch = createEventDispatcher();
</script>

<div>
  <div
    on:click={()=> dispatch('click')}
    class={c([s.checkbox, { [s.active]: selected }])}
  >
    <div class={s.iconCase}>
      <div class={s.icon} />
    </div>
    <div class={s.label}>
      <slot />
    </div>
  </div>
</div>

// packages/react/components/Checkbox/index.jsx
import React from 'react';
import PropTypes from 'prop-types';
import Guide from './Guide';
import c from 'clsx';
import s from '../../../common/Checkbox/index.scss';

function Checkbox({
  selected,
  onClick,
  children
}) {
  return (
    <div
      onClick={onClick}
      className={c(s.checkbox, { [s.active]: selected })}
    >
      <div className={s.iconCase}>
        <div className={s.icon} />
      </div>
      <div className={s.label}>{children}</div>
    </div>
  );
};

Checkbox.Guide = Guide;

Checkbox.propTypes = {
  selected: PropTypes.bool,
  children: PropTypes.object,
  onClick: PropTypes.func
};

Checkbox.defaultProps = {
  selected: false,
  onClick: null
};

export default Checkbox;
