// packages/vue/components/Radio/Guide.vue
<script>
  import { Code, InlineCode as I } from '../../helpers';

  export default {
    components: {
      I, Code,
      'l-radio': () => import('./')
    },
    data() {
      return { active: -1 }
    }
  }
</script>

<template>
  <div>
    <h1>Radio</h1>
    <p>Позволяет выбрать только одно значение из группы</p>
    <Code v="import { l-radio } from 'loft-ui';" />

    <h2>Простой пример</h2>
    <Code v="
      data: ()=> ({ active: -1 }),
      template: `
        <l-radio :active='active'>
          <l-radio-item :value='1'>Select 1</l-radio-item>
          <l-radio-item :value='2'>Select 2</l-radio-item>
        </l-radio>
      `
    " lang="html" />
    <l-radio :active="active">
      <l-radio-item :value='1'>Select 1</l-radio-item>
      <l-radio-item :value='2'>Select 2</l-radio-item>
    </l-radio>
  </div>
</template>

// packages/svelte/components/Radio/Guide.svelte
<script>
  import { Code } from '../../helpers';
  import Radio from './Radio.svelte'

  let active = '';
</script>

<h1>Radio</h1>
<p>Позволяет выбрать только одно значение из группы</p>
<Code v={`import { l-radio } from 'loft-ui';`} />

<Radio active={active}>
  <Radio.Item value="1">Select 1</Radio.Item>
  <Radio.Item value="2">Select 2</Radio.Item>
</Radio>
